# Generated by Django 4.2.7 on 2023-12-01 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('processing', 'processing')], default='pending', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('git_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='experiences',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='experinces',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='ph',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='profil_pic',
            new_name='profile_pic',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='skill',
            new_name='skills',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posterimages'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.studentprofile'),
        ),
        migrations.AddField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.jobs'),
        ),
        migrations.AddField(
            model_name='applications',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
