# Generated by Django 4.2.6 on 2023-12-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
