# Generated by Django 4.2.6 on 2023-12-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_jobs_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='saved_job',
            field=models.ManyToManyField(null=True, related_name='saved', to='myapp.jobs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobs'),
        ),
    ]
